In [41]:
import pandas as pd
import os

pd.set_option('display.max_rows', None)

In [42]:
def get_paths(directory : str, extension : str):
    csv_paths = []
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith(extension):
                csv_paths.append(os.path.join(root, file))
    return csv_paths

In [43]:
def get_num_lines(directory : str):
    csv_file = open(directory, 'r')
    num_lines = sum(1 for _ in csv_file)
    return num_lines

In [44]:
def get_files(extension : str):
    # Replace 'your_directory_path' with the path of the directory you want to search
    directory_path = '.'
    csv_paths = get_paths(directory_path, extension)
    print(len(csv_paths))
    files = []
    for path in csv_paths:
        num_lines = get_num_lines(path)
        if num_lines < 100:
            print(path, num_lines)
        files.append({
            "file_path": path,
            "num_lines": num_lines
        })
    files_data_frame = pd.DataFrame(files)
    files_data_frame = files_data_frame.sort_values(by = ["num_lines"])
    files_data_frame = files_data_frame.reset_index()
    return files_data_frame

In [45]:
csv_data_frame = get_files('.csv')
csv_data_frame

61

    index                                          file_path  num_lines
0      47                     ./sports/stadiums/stadiums.csv        140
1      41                 ./sports/football/competitions.csv        166
2      43            ./sports/football/full/competitions.csv        175
3      59                  ./vnindex/vps/data/industries.csv        178
4      16    ./world/regions/usa/government/institutions.csv        182
5      38                 ./world/independence-days/data.csv        184
6      39                  ./world/independence-days/raw.csv        184
7      45                ./sports/football/fifa/rankings.csv        208
8      37                          ./world/states/states.csv        242
9      40                           ./sports/clubs/clubs.csv        280
10     32  ./world/regions/vietnam/sports/football/standi...        295
11     21           ./world/regions/usa/states/governors.csv        296
12     35                          ./world/cities/cities.csv        340
13     31  ./world/regions/vietnam/sports/football/player...        403
14     44  ./sports/football/clubs/league/standings/datas...        621
15     28         ./world/regions/vietnam/maps/districts.csv        726
16     46                       ./sports/players/players.csv        849
17     53             ./languages/1000-most-common/words.csv       1000
18      3                  ./nobel/transformed/laureates.csv       1048
19      2                              ./nobel/laureates.csv       1048
20     12  ./oracle-of-bacon/data/links/900000-1000000-cu...       1317
21     17  ./world/regions/usa/government/executive/indiv...       1378
22     48                   ./sports/champions/champions.csv       1616
23      1                      ./music/transformed/idols.csv       1779
24      0                                  ./music/idols.csv       1779
25     60               ./vnindex/dragon-capital/history.csv       1901
26     26      ./world/regions/australia/stock/companies.csv       2071
27     25     ./world/regions/australia/stock/statistics.csv       2071
28     58                   ./vnindex/vps/data/companies.csv       2309
29     30  ./world/regions/vietnam/sports/football/matche...       2781
30     51  ./languages/text-classification/input/sample_s...       3264
31     52  ./languages/text-classification/output/submiss...       3264
32     22          ./world/regions/usa/stock/market/nyse.csv       3299
33     23        ./world/regions/usa/stock/market/nasdaq.csv       3371
34     49     ./languages/text-classification/input/test.csv       3700
35     42                        ./sports/football/teams.csv       5001
36     18   ./world/regions/usa/stock-watch/clean/senate.csv       6341
37     29  ./world/regions/vietnam/national-assembly/memb...       6516
38     20     ./world/regions/usa/stock-watch/raw/senate.csv       8306
39     50    ./languages/text-classification/input/train.csv       8562
40     55  ./machine-learning/supervised/house-price-pred...       9359
41     15           ./education/universities/universites.csv       9950
42     27             ./world/regions/vietnam/maps/wards.csv      11563
43     56  ./machine-learning/supervised/employee-retenti...      15000
44     24          ./world/regions/australia/postal-code.csv      16884
45     19      ./world/regions/usa/stock-watch/raw/house.csv      16914
46     34                            ./world/visas/visas.csv      27670
47      4     ./oracle-of-bacon/data/links/800000-900000.csv     100001
48      8          ./oracle-of-bacon/data/links/0-100000.csv     100001
49      6     ./oracle-of-bacon/data/links/700000-800000.csv     100001
50      7     ./oracle-of-bacon/data/links/500000-600000.csv     100001
51      9     ./oracle-of-bacon/data/links/100000-200000.csv     100001
52     11     ./oracle-of-bacon/data/links/400000-500000.csv     100001
53     13     ./oracle-of-bacon/data/links/300000-400000.csv     100001
54     14     ./oracle-of-bacon/data/links/200000-300000.csv     100001
55      5    ./oracle-of-bacon/data/links/900000-1000000.csv     100001
56     10     ./oracle-of-bacon/data/links/600000-700000.csv     100001
57     54         ./languages/1000-most-common/languages.csv     103887
58     33                   ./world/timezones/time_zones.csv     145827
59     36                             ./world/cities/all.csv     209580
60     57                     ./vnindex/vps/data/history.csv    4021643

In [46]:
ipynb_data_frame = get_files('.ipynb')
ipynb_data_frame

46
./oracle-of-bacon/number.ipynb 99
./sports/chess/players/pgn.ipynb 58

    index                                          file_path  num_lines
0      23                   ./sports/chess/players/pgn.ipynb         58
1       4                     ./oracle-of-bacon/number.ipynb         99
2      32                     ./github/gitignores/main.ipynb        110
3      31                 ./languages/detection/detect.ipynb        111
4      33               ./github/codes_of_conduct/main.ipynb        113
5      45               ./vnindex/dragon-capital/query.ipynb        134
6       9               ./world/regions/usa/stock/main.ipynb        155
7      10         ./world/regions/australia/stock/main.ipynb        157
8      24                 ./sports/chess/players/games.ipynb        159
9      39  ./machine-learning/supervised/fashion-mnist/ma...        187
10      3                       ./oracle-of-bacon/main.ipynb        218
11     37  ./machine-learning/supervised/text-classificat...        253
12     43                          ./vnindex/vps/query.ipynb        259
13     14                          ./world/states/main.ipynb        276
14     12                           ./world/visas/main.ipynb        283
15     16                          ./sports/clubs/main.ipynb        288
16     29            ./languages/1000-most-common/main.ipynb        312
17      6                     ./world/regions/usa/main.ipynb        327
18      2                                 ./nobel/main.ipynb        464
19     22                         ./sports/chess/games.ipynb        511
20     15               ./world/independence-days/main.ipynb        524
21     21                          ./sports/chess/main.ipynb        590
22     36  ./machine-learning/supervised/employee-retenti...        721
23     27         ./languages/text-classification/main.ipynb        773
24     35  ./machine-learning/supervised/linear-regressio...        775
25     40  ./machine-learning/supervised/marketing-cost/m...        777
26     25               ./sports/chess/players/analyse.ipynb        807
27     42  ./machine-learning/supervised/length-conversio...        964
28      8              ./world/regions/usa/states/main.ipynb        986
29      1                                 ./music/main.ipynb       1022
30      0                                      ./files.ipynb       1106
31     34  ./machine-learning/supervised/house-price-pred...       1122
32     41  ./machine-learning/supervised/linear-regressio...       1207
33     20                        ./sports/players/main.ipynb       1219
34     11                       ./world/timezones/main.ipynb       1258
35     18  ./sports/football/clubs/league/standings/main....       1369
36     38  ./machine-learning/supervised/fuel-efficiency/...       1535
37      7  ./world/regions/usa/government/executive/usa.i...       1800
38     26                      ./sports/champions/main.ipynb       2202
39     17                  ./sports/football/full/main.ipynb       3060
40      5                ./education/universities/main.ipynb       3088
41     19                  ./sports/football/fifa/main.ipynb       3123
42     13                          ./world/cities/main.ipynb       3350
43     30                   ./languages/detection/main.ipynb       5252
44     28                     ./languages/popular/main.ipynb      20279
45     44                        ./vnindex/vps/analyse.ipynb     119393

In [47]:
md_data_frame = get_files('.md')
md_data_frame

3
./github/codes_of_conduct/docs/Citizen Code Of Conduct.md 94

   index                                          file_path  num_lines
0      1  ./github/codes_of_conduct/docs/Citizen Code Of...         94
1      2  ./github/codes_of_conduct/docs/Contributor Cov...        128
2      0                 ./education/universities/README.md       1730

In [48]:
txt_data_frame = get_files('.txt')
txt_data_frame

1
./requirements.txt 13

   index           file_path  num_lines
0      0  ./requirements.txt         13